// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: src/lib/vault.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface PqVault {
  /** 32-byte Argon2 salt */
  salt: Uint8Array;
  /** IV for the Argon2-wrapped PQC key */
  argon2Iv: Uint8Array;
  /** The ML-KEM-768 encapsulated key */
  pqcWrappedKey: Uint8Array;
  /** The ML-KEM private key, AES-encrypted by (Pass + Keyfile) */
  pqcPrivateKeyEnc: Uint8Array;
  /** The actual vault data (AES-256-GCM) */
  encryptedPayload: Uint8Array;
  /** IV for the main payload */
  payloadIv: Uint8Array;
}

function createBasePqVault(): PqVault {
  return {
    salt: new Uint8Array(0),
    argon2Iv: new Uint8Array(0),
    pqcWrappedKey: new Uint8Array(0),
    pqcPrivateKeyEnc: new Uint8Array(0),
    encryptedPayload: new Uint8Array(0),
    payloadIv: new Uint8Array(0),
  };
}

export const PqVault: MessageFns<PqVault> = {
  encode(message: PqVault, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.salt.length !== 0) {
      writer.uint32(10).bytes(message.salt);
    }
    if (message.argon2Iv.length !== 0) {
      writer.uint32(18).bytes(message.argon2Iv);
    }
    if (message.pqcWrappedKey.length !== 0) {
      writer.uint32(26).bytes(message.pqcWrappedKey);
    }
    if (message.pqcPrivateKeyEnc.length !== 0) {
      writer.uint32(34).bytes(message.pqcPrivateKeyEnc);
    }
    if (message.encryptedPayload.length !== 0) {
      writer.uint32(42).bytes(message.encryptedPayload);
    }
    if (message.payloadIv.length !== 0) {
      writer.uint32(50).bytes(message.payloadIv);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PqVault {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePqVault();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.salt = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.argon2Iv = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pqcWrappedKey = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.pqcPrivateKeyEnc = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.encryptedPayload = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.payloadIv = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PqVault {
    return {
      salt: isSet(object.salt) ? bytesFromBase64(object.salt) : new Uint8Array(0),
      argon2Iv: isSet(object.argon2Iv)
        ? bytesFromBase64(object.argon2Iv)
        : isSet(object.argon2_iv)
        ? bytesFromBase64(object.argon2_iv)
        : new Uint8Array(0),
      pqcWrappedKey: isSet(object.pqcWrappedKey)
        ? bytesFromBase64(object.pqcWrappedKey)
        : isSet(object.pqc_wrapped_key)
        ? bytesFromBase64(object.pqc_wrapped_key)
        : new Uint8Array(0),
      pqcPrivateKeyEnc: isSet(object.pqcPrivateKeyEnc)
        ? bytesFromBase64(object.pqcPrivateKeyEnc)
        : isSet(object.pqc_private_key_enc)
        ? bytesFromBase64(object.pqc_private_key_enc)
        : new Uint8Array(0),
      encryptedPayload: isSet(object.encryptedPayload)
        ? bytesFromBase64(object.encryptedPayload)
        : isSet(object.encrypted_payload)
        ? bytesFromBase64(object.encrypted_payload)
        : new Uint8Array(0),
      payloadIv: isSet(object.payloadIv)
        ? bytesFromBase64(object.payloadIv)
        : isSet(object.payload_iv)
        ? bytesFromBase64(object.payload_iv)
        : new Uint8Array(0),
    };
  },

  toJSON(message: PqVault): unknown {
    const obj: any = {};
    if (message.salt.length !== 0) {
      obj.salt = base64FromBytes(message.salt);
    }
    if (message.argon2Iv.length !== 0) {
      obj.argon2Iv = base64FromBytes(message.argon2Iv);
    }
    if (message.pqcWrappedKey.length !== 0) {
      obj.pqcWrappedKey = base64FromBytes(message.pqcWrappedKey);
    }
    if (message.pqcPrivateKeyEnc.length !== 0) {
      obj.pqcPrivateKeyEnc = base64FromBytes(message.pqcPrivateKeyEnc);
    }
    if (message.encryptedPayload.length !== 0) {
      obj.encryptedPayload = base64FromBytes(message.encryptedPayload);
    }
    if (message.payloadIv.length !== 0) {
      obj.payloadIv = base64FromBytes(message.payloadIv);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PqVault>, I>>(base?: I): PqVault {
    return PqVault.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PqVault>, I>>(object: I): PqVault {
    const message = createBasePqVault();
    message.salt = object.salt ?? new Uint8Array(0);
    message.argon2Iv = object.argon2Iv ?? new Uint8Array(0);
    message.pqcWrappedKey = object.pqcWrappedKey ?? new Uint8Array(0);
    message.pqcPrivateKeyEnc = object.pqcPrivateKeyEnc ?? new Uint8Array(0);
    message.encryptedPayload = object.encryptedPayload ?? new Uint8Array(0);
    message.payloadIv = object.payloadIv ?? new Uint8Array(0);
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
